name: Deploy React App to Bluehost

on:
  push:
    branches:
      - main  # Triggers the script when you push to the main branch

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: ⚙️ Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 🔨 Install Dependencies & Build
      run: |
        npm install
        npm run build
        cp -r api ./dist/

    - name: 🚀 Sync Files to Bluehost
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/  # Use ./build/ if you are using Create React App instead of Vite
        server-dir: /jasti.pasacouncil.org/  # Change this to your specific Bluehost folder if needed